create table if not exists PUBLIC.genres
(
    id  BIGINT AUTO_INCREMENT,
   -- id          INTEGER generated by default as identity primary key,
    genres_name varchar NOT NULL ,
    CONSTRAINT "GENRE_PK"
PRIMARY KEY (ID)
);

create table if not exists PUBLIC.film_rating
(
    id               INTEGER generated by default as identity primary key,
    film_rating_name varchar

);

create table if not exists PUBLIC.mpa
(
    mpa_id   INTEGER,
    mpa_name varchar
);


create table if not exists PUBLIC.films
(
    id          INTEGER generated by default as identity primary key,
    genres      INTEGER ,
    name        character(60) NOT NULL,
    description character(200),
    releaseDate timestamp,
    duration    INTEGER,
    rate        INTEGER,
    mpa         INTEGER
);




create table if not exists PUBLIC.users
(
    id       INTEGER generated by default as identity primary key,
    email    character(100) NOT NULL,
    login    character(100) NOT NULL,
    name     character(100),
    birthday timestamp
);

create table if not exists PUBLIC.users_friend
(
    user_id   INTEGER REFERENCES users(id),
    friend_id INTEGER REFERENCES users(id),
 --   status    boolean,
       constraint PK_USERS_FRIEND
            primary key (user_id, friend_id)
 --   constraint FK_USER_FRIEND_USER
 --       FOREIGN KEY (user_id) REFERENCES users,
 --   constraint FK_USER_FRIEND_FRIEND
 --       FOREIGN KEY (friend_id) references users
);

create table if not exists PUBLIC.film_likes
(
    user_id INTEGER REFERENCES users (id),
    film_id INTEGER REFERENCES films (id)
);

create table if not exists PUBLIC.films_genres
(
    FILM_ID  INTEGER not null REFERENCES films (id),
    GENRE_ID INTEGER not null references genres (id)
 --   constraint PK_GENRE_FILM
--        primary key (FILM_ID, GENRE_ID),
 --   constraint FK_GENRES_FILMS_FILM
 --       FOREIGN KEY (FILM_ID) REFERENCES films,
 --   constraint FK_GENRE_FILMS_GENRE
 --       FOREIGN KEY (GENRE_ID) references GENRES
);

insert into mpa  (mpa_id, mpa_name) values (1,'G');

insert into mpa (mpa_id, mpa_name) values (2,'PG') ;

insert into mpa (mpa_id, mpa_name) values (3,'PG-13');

insert into mpa (mpa_id, mpa_name) values (4,'R');

merge into  genres key ( id)  values (1,'Комедия' );

merge into genres key ( id) values (2, 'Драма' );

--merge into genres key ( id) values ( 3,'Мультфильм' );

--merge into genres key ( id) values (4,'Триллер' );

--merge into genres key ( id) values (5,'Документальный' );

--merge into genres key ( id) values (6, 'Боевик' );


--insert into mpa (id, mpa_name) values (1, 'G');
--insert into mpa (id, mpa_name) values (2, 'PG');
--insert into mpa (id, mpa_name) values ( 3, 'PG-13' );
--insert into mpa (id, mpa_name) values ( 4, 'R' );
insert into mpa (mpa_id, mpa_name) values ( 5,'NC-17');

--insert into genres (genres_name) values ( 'Жанр' );

-- create unique index
--    on genres (id);




